import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { StarsBackground } from "./components/ui/stars-background";
import { ShootingStars } from "./components/ui/shooting-stars";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <div className="min-h-screen">
          {children}
          <ShootingStars />
          <StarsBackground />
        </div>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
